
package client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-09T20:18:44.942+01:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "rasporedFault", targetNamespace = "http://www.example.org/rasporedcasova/")
public class GetRasporedFaultException extends Exception {
    
    private client.RasporedFaultType rasporedFault;

    public GetRasporedFaultException() {
        super();
    }
    
    public GetRasporedFaultException(String message) {
        super(message);
    }
    
    public GetRasporedFaultException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetRasporedFaultException(String message, client.RasporedFaultType rasporedFault) {
        super(message);
        this.rasporedFault = rasporedFault;
    }

    public GetRasporedFaultException(String message, client.RasporedFaultType rasporedFault, Throwable cause) {
        super(message, cause);
        this.rasporedFault = rasporedFault;
    }

    public client.RasporedFaultType getFaultInfo() {
        return this.rasporedFault;
    }
}
