//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 12:43:06 PM CET 
//


package com.jovic;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="popunjavaStudent">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="brIndexa">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;length value="6"/>
 *                         &lt;pattern value="[0-9]{3}[/][0-9]{2}"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Departman">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="Matematiku i Informatiku"/>
 *                         &lt;enumeration value="Fiziku"/>
 *                         &lt;enumeration value="Biologiju"/>
 *                         &lt;enumeration value="Geografiju i hotelijerstvo"/>
 *                         &lt;enumeration value="Hemiju"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="StepenStudija">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="Osnovne"/>
 *                         &lt;enumeration value="Diplomske"/>
 *                         &lt;enumeration value="Doktorske"/>
 *                         &lt;enumeration value="Specijalisti\u010dke"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="StudijskiProgram">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="Osnovne studije - Matematika"/>
 *                         &lt;enumeration value="Osnovne studije - Primenjena Matematika"/>
 *                         &lt;enumeration value="Osnovne studije - Informatika"/>
 *                         &lt;enumeration value="Master studije - Matematika"/>
 *                         &lt;enumeration value="Master studije - Primenjena Matematika"/>
 *                         &lt;enumeration value="Master studije - Informatika"/>
 *                         &lt;enumeration value="Doktorske studije - Informatika"/>
 *                         &lt;enumeration value="Doktorske studije - Matematika"/>
 *                         &lt;enumeration value="Biolog"/>
 *                         &lt;enumeration value="Diplomirani biolog - Master"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Plan">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;length value="9"/>
 *                         &lt;pattern value="[0-9]{4}[/][0-9]{4}"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="IspitniRok">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="januarskom"/>
 *                         &lt;enumeration value="aprilskom"/>
 *                         &lt;enumeration value="junskom"/>
 *                         &lt;enumeration value="septembarskom"/>
 *                         &lt;enumeration value="oktobar I"/>
 *                         &lt;enumeration value="oktobar II"/>
 *                         &lt;enumeration value="oktobar III"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Student">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="PrezimeStudenta" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ImeStudenta" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="NacinFinansiranja">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="budzet"/>
 *                         &lt;enumeration value="samofinansiranje"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Predmet" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Profesor">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ImeProfesora" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Prezime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="BrojPolaganja" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DatumPrijave" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="Potpis" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="popunjavaProfesor">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PolozenPredmet" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="Rezultat">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="BrojPoena">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                                   &lt;minInclusive value="1"/>
 *                                   &lt;maxInclusive value="100"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="Ocena" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="sifra" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="FondCasova">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;length value="5"/>
 *                         &lt;pattern value="[0-9]{1}[+][0-9]{1}[+][0-9]{1}"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="ESPB">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                         &lt;minInclusive value="1"/>
 *                         &lt;maxInclusive value="9"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="DatumPolaganja" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="PotpisNastavnika" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "popunjavaStudent",
    "popunjavaProfesor"
})
@XmlRootElement(name = "IspitnaPrijava")
public class IspitnaPrijava {

    @XmlElement(required = true)
    protected IspitnaPrijava.PopunjavaStudent popunjavaStudent;
    @XmlElement(required = true)
    protected IspitnaPrijava.PopunjavaProfesor popunjavaProfesor;

    /**
     * Gets the value of the popunjavaStudent property.
     * 
     * @return
     *     possible object is
     *     {@link IspitnaPrijava.PopunjavaStudent }
     *     
     */
    public IspitnaPrijava.PopunjavaStudent getPopunjavaStudent() {
        return popunjavaStudent;
    }

    /**
     * Sets the value of the popunjavaStudent property.
     * 
     * @param value
     *     allowed object is
     *     {@link IspitnaPrijava.PopunjavaStudent }
     *     
     */
    public void setPopunjavaStudent(IspitnaPrijava.PopunjavaStudent value) {
        this.popunjavaStudent = value;
    }

    /**
     * Gets the value of the popunjavaProfesor property.
     * 
     * @return
     *     possible object is
     *     {@link IspitnaPrijava.PopunjavaProfesor }
     *     
     */
    public IspitnaPrijava.PopunjavaProfesor getPopunjavaProfesor() {
        return popunjavaProfesor;
    }

    /**
     * Sets the value of the popunjavaProfesor property.
     * 
     * @param value
     *     allowed object is
     *     {@link IspitnaPrijava.PopunjavaProfesor }
     *     
     */
    public void setPopunjavaProfesor(IspitnaPrijava.PopunjavaProfesor value) {
        this.popunjavaProfesor = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PolozenPredmet" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="Rezultat">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="BrojPoena">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *                         &lt;minInclusive value="1"/>
     *                         &lt;maxInclusive value="100"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="Ocena" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="sifra" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="FondCasova">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;length value="5"/>
     *               &lt;pattern value="[0-9]{1}[+][0-9]{1}[+][0-9]{1}"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="ESPB">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *               &lt;minInclusive value="1"/>
     *               &lt;maxInclusive value="9"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="DatumPolaganja" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="PotpisNastavnika" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "polozenPredmet",
        "rezultat",
        "sifra",
        "fondCasova",
        "espb",
        "datumPolaganja",
        "potpisNastavnika"
    })
    public static class PopunjavaProfesor {

        @XmlElement(name = "PolozenPredmet", required = true)
        protected Object polozenPredmet;
        @XmlElement(name = "Rezultat", required = true)
        protected IspitnaPrijava.PopunjavaProfesor.Rezultat rezultat;
        @XmlElement(required = true)
        protected String sifra;
        @XmlElement(name = "FondCasova", required = true)
        protected String fondCasova;
        @XmlElement(name = "ESPB")
        protected int espb;
        @XmlElement(name = "DatumPolaganja", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar datumPolaganja;
        @XmlElement(name = "PotpisNastavnika", required = true)
        protected String potpisNastavnika;

        /**
         * Gets the value of the polozenPredmet property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getPolozenPredmet() {
            return polozenPredmet;
        }

        /**
         * Sets the value of the polozenPredmet property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setPolozenPredmet(Object value) {
            this.polozenPredmet = value;
        }

        /**
         * Gets the value of the rezultat property.
         * 
         * @return
         *     possible object is
         *     {@link IspitnaPrijava.PopunjavaProfesor.Rezultat }
         *     
         */
        public IspitnaPrijava.PopunjavaProfesor.Rezultat getRezultat() {
            return rezultat;
        }

        /**
         * Sets the value of the rezultat property.
         * 
         * @param value
         *     allowed object is
         *     {@link IspitnaPrijava.PopunjavaProfesor.Rezultat }
         *     
         */
        public void setRezultat(IspitnaPrijava.PopunjavaProfesor.Rezultat value) {
            this.rezultat = value;
        }

        /**
         * Gets the value of the sifra property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSifra() {
            return sifra;
        }

        /**
         * Sets the value of the sifra property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSifra(String value) {
            this.sifra = value;
        }

        /**
         * Gets the value of the fondCasova property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFondCasova() {
            return fondCasova;
        }

        /**
         * Sets the value of the fondCasova property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFondCasova(String value) {
            this.fondCasova = value;
        }

        /**
         * Gets the value of the espb property.
         * 
         */
        public int getESPB() {
            return espb;
        }

        /**
         * Sets the value of the espb property.
         * 
         */
        public void setESPB(int value) {
            this.espb = value;
        }

        /**
         * Gets the value of the datumPolaganja property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatumPolaganja() {
            return datumPolaganja;
        }

        /**
         * Sets the value of the datumPolaganja property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatumPolaganja(XMLGregorianCalendar value) {
            this.datumPolaganja = value;
        }

        /**
         * Gets the value of the potpisNastavnika property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPotpisNastavnika() {
            return potpisNastavnika;
        }

        /**
         * Sets the value of the potpisNastavnika property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPotpisNastavnika(String value) {
            this.potpisNastavnika = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="BrojPoena">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
         *               &lt;minInclusive value="1"/>
         *               &lt;maxInclusive value="100"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="Ocena" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "brojPoena",
            "ocena"
        })
        public static class Rezultat {

            @XmlElement(name = "BrojPoena")
            protected int brojPoena;
            @XmlElement(name = "Ocena", required = true)
            protected String ocena;

            /**
             * Gets the value of the brojPoena property.
             * 
             */
            public int getBrojPoena() {
                return brojPoena;
            }

            /**
             * Sets the value of the brojPoena property.
             * 
             */
            public void setBrojPoena(int value) {
                this.brojPoena = value;
            }

            /**
             * Gets the value of the ocena property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOcena() {
                return ocena;
            }

            /**
             * Sets the value of the ocena property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOcena(String value) {
                this.ocena = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="brIndexa">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;length value="6"/>
     *               &lt;pattern value="[0-9]{3}[/][0-9]{2}"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Departman">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="Matematiku i Informatiku"/>
     *               &lt;enumeration value="Fiziku"/>
     *               &lt;enumeration value="Biologiju"/>
     *               &lt;enumeration value="Geografiju i hotelijerstvo"/>
     *               &lt;enumeration value="Hemiju"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="StepenStudija">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="Osnovne"/>
     *               &lt;enumeration value="Diplomske"/>
     *               &lt;enumeration value="Doktorske"/>
     *               &lt;enumeration value="Specijalisti\u010dke"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="StudijskiProgram">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="Osnovne studije - Matematika"/>
     *               &lt;enumeration value="Osnovne studije - Primenjena Matematika"/>
     *               &lt;enumeration value="Osnovne studije - Informatika"/>
     *               &lt;enumeration value="Master studije - Matematika"/>
     *               &lt;enumeration value="Master studije - Primenjena Matematika"/>
     *               &lt;enumeration value="Master studije - Informatika"/>
     *               &lt;enumeration value="Doktorske studije - Informatika"/>
     *               &lt;enumeration value="Doktorske studije - Matematika"/>
     *               &lt;enumeration value="Biolog"/>
     *               &lt;enumeration value="Diplomirani biolog - Master"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Plan">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;length value="9"/>
     *               &lt;pattern value="[0-9]{4}[/][0-9]{4}"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="IspitniRok">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="januarskom"/>
     *               &lt;enumeration value="aprilskom"/>
     *               &lt;enumeration value="junskom"/>
     *               &lt;enumeration value="septembarskom"/>
     *               &lt;enumeration value="oktobar I"/>
     *               &lt;enumeration value="oktobar II"/>
     *               &lt;enumeration value="oktobar III"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Student">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="PrezimeStudenta" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ImeStudenta" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="NacinFinansiranja">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="budzet"/>
     *               &lt;enumeration value="samofinansiranje"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Predmet" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Profesor">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ImeProfesora" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Prezime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="BrojPolaganja" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="DatumPrijave" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="Potpis" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "brIndexa",
        "departman",
        "stepenStudija",
        "studijskiProgram",
        "plan",
        "ispitniRok",
        "student",
        "nacinFinansiranja",
        "predmet",
        "profesor",
        "brojPolaganja",
        "datumPrijave",
        "potpis"
    })
    public static class PopunjavaStudent {

        @XmlElement(required = true)
        protected String brIndexa;
        @XmlElement(name = "Departman", required = true)
        protected String departman;
        @XmlElement(name = "StepenStudija", required = true)
        protected String stepenStudija;
        @XmlElement(name = "StudijskiProgram", required = true)
        protected String studijskiProgram;
        @XmlElement(name = "Plan", required = true)
        protected String plan;
        @XmlElement(name = "IspitniRok", required = true)
        protected String ispitniRok;
        @XmlElement(name = "Student", required = true)
        protected IspitnaPrijava.PopunjavaStudent.Student student;
        @XmlElement(name = "NacinFinansiranja", required = true)
        protected String nacinFinansiranja;
        @XmlElement(name = "Predmet", required = true)
        protected String predmet;
        @XmlElement(name = "Profesor", required = true)
        protected IspitnaPrijava.PopunjavaStudent.Profesor profesor;
        @XmlElement(name = "BrojPolaganja", required = true)
        protected String brojPolaganja;
        @XmlElement(name = "DatumPrijave", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar datumPrijave;
        @XmlElement(name = "Potpis", required = true)
        protected String potpis;

        /**
         * Gets the value of the brIndexa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBrIndexa() {
            return brIndexa;
        }

        /**
         * Sets the value of the brIndexa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBrIndexa(String value) {
            this.brIndexa = value;
        }

        /**
         * Gets the value of the departman property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDepartman() {
            return departman;
        }

        /**
         * Sets the value of the departman property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDepartman(String value) {
            this.departman = value;
        }

        /**
         * Gets the value of the stepenStudija property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStepenStudija() {
            return stepenStudija;
        }

        /**
         * Sets the value of the stepenStudija property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStepenStudija(String value) {
            this.stepenStudija = value;
        }

        /**
         * Gets the value of the studijskiProgram property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStudijskiProgram() {
            return studijskiProgram;
        }

        /**
         * Sets the value of the studijskiProgram property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStudijskiProgram(String value) {
            this.studijskiProgram = value;
        }

        /**
         * Gets the value of the plan property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlan() {
            return plan;
        }

        /**
         * Sets the value of the plan property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlan(String value) {
            this.plan = value;
        }

        /**
         * Gets the value of the ispitniRok property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIspitniRok() {
            return ispitniRok;
        }

        /**
         * Sets the value of the ispitniRok property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIspitniRok(String value) {
            this.ispitniRok = value;
        }

        /**
         * Gets the value of the student property.
         * 
         * @return
         *     possible object is
         *     {@link IspitnaPrijava.PopunjavaStudent.Student }
         *     
         */
        public IspitnaPrijava.PopunjavaStudent.Student getStudent() {
            return student;
        }

        /**
         * Sets the value of the student property.
         * 
         * @param value
         *     allowed object is
         *     {@link IspitnaPrijava.PopunjavaStudent.Student }
         *     
         */
        public void setStudent(IspitnaPrijava.PopunjavaStudent.Student value) {
            this.student = value;
        }

        /**
         * Gets the value of the nacinFinansiranja property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNacinFinansiranja() {
            return nacinFinansiranja;
        }

        /**
         * Sets the value of the nacinFinansiranja property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNacinFinansiranja(String value) {
            this.nacinFinansiranja = value;
        }

        /**
         * Gets the value of the predmet property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPredmet() {
            return predmet;
        }

        /**
         * Sets the value of the predmet property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPredmet(String value) {
            this.predmet = value;
        }

        /**
         * Gets the value of the profesor property.
         * 
         * @return
         *     possible object is
         *     {@link IspitnaPrijava.PopunjavaStudent.Profesor }
         *     
         */
        public IspitnaPrijava.PopunjavaStudent.Profesor getProfesor() {
            return profesor;
        }

        /**
         * Sets the value of the profesor property.
         * 
         * @param value
         *     allowed object is
         *     {@link IspitnaPrijava.PopunjavaStudent.Profesor }
         *     
         */
        public void setProfesor(IspitnaPrijava.PopunjavaStudent.Profesor value) {
            this.profesor = value;
        }

        /**
         * Gets the value of the brojPolaganja property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBrojPolaganja() {
            return brojPolaganja;
        }

        /**
         * Sets the value of the brojPolaganja property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBrojPolaganja(String value) {
            this.brojPolaganja = value;
        }

        /**
         * Gets the value of the datumPrijave property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatumPrijave() {
            return datumPrijave;
        }

        /**
         * Sets the value of the datumPrijave property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatumPrijave(XMLGregorianCalendar value) {
            this.datumPrijave = value;
        }

        /**
         * Gets the value of the potpis property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPotpis() {
            return potpis;
        }

        /**
         * Sets the value of the potpis property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPotpis(String value) {
            this.potpis = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ImeProfesora" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Prezime" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "imeProfesora",
            "prezime"
        })
        public static class Profesor {

            @XmlElement(name = "ImeProfesora", required = true)
            protected String imeProfesora;
            @XmlElement(name = "Prezime", required = true)
            protected String prezime;

            /**
             * Gets the value of the imeProfesora property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getImeProfesora() {
                return imeProfesora;
            }

            /**
             * Sets the value of the imeProfesora property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setImeProfesora(String value) {
                this.imeProfesora = value;
            }

            /**
             * Gets the value of the prezime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPrezime() {
                return prezime;
            }

            /**
             * Sets the value of the prezime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPrezime(String value) {
                this.prezime = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="PrezimeStudenta" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ImeStudenta" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "prezimeStudenta",
            "imeStudenta"
        })
        public static class Student {

            @XmlElement(name = "PrezimeStudenta", required = true)
            protected String prezimeStudenta;
            @XmlElement(name = "ImeStudenta", required = true)
            protected String imeStudenta;

            /**
             * Gets the value of the prezimeStudenta property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPrezimeStudenta() {
                return prezimeStudenta;
            }

            /**
             * Sets the value of the prezimeStudenta property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPrezimeStudenta(String value) {
                this.prezimeStudenta = value;
            }

            /**
             * Gets the value of the imeStudenta property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getImeStudenta() {
                return imeStudenta;
            }

            /**
             * Sets the value of the imeStudenta property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setImeStudenta(String value) {
                this.imeStudenta = value;
            }

        }

    }

}
