//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 12:43:06 PM CET 
//


package com.jovic;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.jovic package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.jovic
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IspitnaPrijava }
     * 
     */
    public IspitnaPrijava createIspitnaPrijava() {
        return new IspitnaPrijava();
    }

    /**
     * Create an instance of {@link IspitnaPrijava.PopunjavaProfesor }
     * 
     */
    public IspitnaPrijava.PopunjavaProfesor createIspitnaPrijavaPopunjavaProfesor() {
        return new IspitnaPrijava.PopunjavaProfesor();
    }

    /**
     * Create an instance of {@link IspitnaPrijava.PopunjavaStudent }
     * 
     */
    public IspitnaPrijava.PopunjavaStudent createIspitnaPrijavaPopunjavaStudent() {
        return new IspitnaPrijava.PopunjavaStudent();
    }

    /**
     * Create an instance of {@link IspitnaPrijava.PopunjavaProfesor.Rezultat }
     * 
     */
    public IspitnaPrijava.PopunjavaProfesor.Rezultat createIspitnaPrijavaPopunjavaProfesorRezultat() {
        return new IspitnaPrijava.PopunjavaProfesor.Rezultat();
    }

    /**
     * Create an instance of {@link IspitnaPrijava.PopunjavaStudent.Student }
     * 
     */
    public IspitnaPrijava.PopunjavaStudent.Student createIspitnaPrijavaPopunjavaStudentStudent() {
        return new IspitnaPrijava.PopunjavaStudent.Student();
    }

    /**
     * Create an instance of {@link IspitnaPrijava.PopunjavaStudent.Profesor }
     * 
     */
    public IspitnaPrijava.PopunjavaStudent.Profesor createIspitnaPrijavaPopunjavaStudentProfesor() {
        return new IspitnaPrijava.PopunjavaStudent.Profesor();
    }

}
