package service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.5
 * 2017-03-28T23:03:22.241+02:00
 * Generated source version: 3.0.5
 * 
 */
@WebService(targetNamespace = "http://new.webservice.namespace", name = "StudentPortTypes")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface StudentPortTypes {

    @WebMethod
    @WebResult(name = "studenti", targetNamespace = "http://new.webservice.namespace", partName = "studenti")
    public Studenti pronadjiStudenta(
        @WebParam(partName = "fakultet", name = "naziv_fakulteta", targetNamespace = "http://new.webservice.namespace")
        java.lang.String fakultet
    ) throws PronadjiStudentaFault;
}
