//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.08 at 08:38:38 PM CET 
//


package model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="requestMsg">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="student">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="brIndeksa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="predmet" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="responseMsg">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="detaljiIspita">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="brojPoena" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="ocena" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="errorMsg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "requestMsg",
    "responseMsg"
})
@XmlRootElement(name = "message")
public class Message {

    protected Message.RequestMsg requestMsg;
    protected Message.ResponseMsg responseMsg;

    /**
     * Gets the value of the requestMsg property.
     * 
     * @return
     *     possible object is
     *     {@link Message.RequestMsg }
     *     
     */
    public Message.RequestMsg getRequestMsg() {
        return requestMsg;
    }

    /**
     * Sets the value of the requestMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link Message.RequestMsg }
     *     
     */
    public void setRequestMsg(Message.RequestMsg value) {
        this.requestMsg = value;
    }

    /**
     * Gets the value of the responseMsg property.
     * 
     * @return
     *     possible object is
     *     {@link Message.ResponseMsg }
     *     
     */
    public Message.ResponseMsg getResponseMsg() {
        return responseMsg;
    }

    /**
     * Sets the value of the responseMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link Message.ResponseMsg }
     *     
     */
    public void setResponseMsg(Message.ResponseMsg value) {
        this.responseMsg = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="student">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="brIndeksa" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="predmet" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "student",
        "predmet"
    })
    public static class RequestMsg {

        @XmlElement(required = true)
        protected Message.RequestMsg.Student student;
        @XmlElement(required = true)
        protected String predmet;

        /**
         * Gets the value of the student property.
         * 
         * @return
         *     possible object is
         *     {@link Message.RequestMsg.Student }
         *     
         */
        public Message.RequestMsg.Student getStudent() {
            return student;
        }

        /**
         * Sets the value of the student property.
         * 
         * @param value
         *     allowed object is
         *     {@link Message.RequestMsg.Student }
         *     
         */
        public void setStudent(Message.RequestMsg.Student value) {
            this.student = value;
        }

        /**
         * Gets the value of the predmet property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPredmet() {
            return predmet;
        }

        /**
         * Sets the value of the predmet property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPredmet(String value) {
            this.predmet = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="brIndeksa" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "ime",
            "prezime",
            "brIndeksa"
        })
        public static class Student {

            @XmlElement(required = true)
            protected String ime;
            @XmlElement(required = true)
            protected String prezime;
            @XmlElement(required = true)
            protected String brIndeksa;

            /**
             * Gets the value of the ime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIme() {
                return ime;
            }

            /**
             * Sets the value of the ime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIme(String value) {
                this.ime = value;
            }

            /**
             * Gets the value of the prezime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPrezime() {
                return prezime;
            }

            /**
             * Sets the value of the prezime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPrezime(String value) {
                this.prezime = value;
            }

            /**
             * Gets the value of the brIndeksa property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBrIndeksa() {
                return brIndeksa;
            }

            /**
             * Sets the value of the brIndeksa property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBrIndeksa(String value) {
                this.brIndeksa = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="detaljiIspita">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="brojPoena" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="ocena" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="errorMsg" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "detaljiIspita",
        "errorMsg"
    })
    public static class ResponseMsg {

        protected Message.ResponseMsg.DetaljiIspita detaljiIspita;
        protected String errorMsg;

        /**
         * Gets the value of the detaljiIspita property.
         * 
         * @return
         *     possible object is
         *     {@link Message.ResponseMsg.DetaljiIspita }
         *     
         */
        public Message.ResponseMsg.DetaljiIspita getDetaljiIspita() {
            return detaljiIspita;
        }

        /**
         * Sets the value of the detaljiIspita property.
         * 
         * @param value
         *     allowed object is
         *     {@link Message.ResponseMsg.DetaljiIspita }
         *     
         */
        public void setDetaljiIspita(Message.ResponseMsg.DetaljiIspita value) {
            this.detaljiIspita = value;
        }

        /**
         * Gets the value of the errorMsg property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getErrorMsg() {
            return errorMsg;
        }

        /**
         * Sets the value of the errorMsg property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setErrorMsg(String value) {
            this.errorMsg = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="brojPoena" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="ocena" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "brojPoena",
            "ocena"
        })
        public static class DetaljiIspita {

            protected int brojPoena;
            protected int ocena;

            /**
             * Gets the value of the brojPoena property.
             * 
             */
            public int getBrojPoena() {
                return brojPoena;
            }

            /**
             * Sets the value of the brojPoena property.
             * 
             */
            public void setBrojPoena(int value) {
                this.brojPoena = value;
            }

            /**
             * Gets the value of the ocena property.
             * 
             */
            public int getOcena() {
                return ocena;
            }

            /**
             * Sets the value of the ocena property.
             * 
             */
            public void setOcena(int value) {
                this.ocena = value;
            }

        }

    }

}
